In [1]:
import torch
import numpy as np
import warnings # Ignore warnings
warnings.filterwarnings('ignore')

In [2]:
print("Torch Version:", torch.__version__)
print("Numpy Version:", np.__version__)

Torch Version: 2.4.0+cu118
Numpy Version: 1.26.4


Tensor Initilization

In [3]:
device="cuda" if torch.cuda.is_available() else "cpu" # Check CUDA and set device

In [4]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32,device=device, requires_grad=True)

In [5]:
print(my_tensor)
print("Data Type:", my_tensor.dtype)
print("Device:",my_tensor.device)
print("Shape:",my_tensor.shape)
print("Requires Gradient:",my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
Data Type: torch.float32
Device: cuda:0
Shape: torch.Size([2, 3])
Requires Gradient: True


In [6]:
# Empty Tensor 
x1=torch.empty(3,3)
print("Empty Tensor:\n",x1)

# Tensor filled with Zeros
x2=torch.zeros(3,3)
print("Zero Tensor:\n",x2)

# Tensor with random values
x3=torch.rand(3,3)
print("Random Tensor:\n",x3)

# Tensor filled with ones
x4=torch.ones(3,3)
print("Ones Tensor:\n",x4)

# Identity Matrix
x5=torch.eye(4,4)
print("Identity Matrix:\n",x5)

# Tensor using Arange
x6=torch.arange(5)
print("Arange Tensor:\n",x6)

# Tensor using linspace
x7=torch.linspace(0.1,1,5)
print("Linspace Tensor:\n",x7)

# Tensor with normal distribution
x8=torch.empty(1,5).normal_(mean=0,std=1)
print("Normal Distribution Tensor:\n",x8)

# Tensor with uniform distribution
x9=torch.empty(1,5).uniform_(0,1)
print("Uniform Distribution Tensor:\n",x9)

Empty Tensor:
 tensor([[-1.0300e+31,  1.0972e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
Zero Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Random Tensor:
 tensor([[0.7138, 0.3200, 0.8804],
        [0.2940, 0.0202, 0.2855],
        [0.6265, 0.4699, 0.0013]])
Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Identity Matrix:
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Arange Tensor:
 tensor([0, 1, 2, 3, 4])
Linspace Tensor:
 tensor([0.1000, 0.3250, 0.5500, 0.7750, 1.0000])
Normal Distribution Tensor:
 tensor([[-1.5519,  0.3141, -1.8716, -0.1535,  0.9671]])
Uniform Distribution Tensor:
 tensor([[0.3533, 0.5893, 0.1097, 0.6548, 0.0850]])


In [7]:
tensor=torch.arange(4)
print("Boolean Tensor:", tensor.bool()) # Boolean
print("Short Tensor (int16):", tensor.short()) # int16
print("Long Tensor (int64):", tensor.long()) # int64
print("Half Tensor (float16):", tensor.half()) # float16
print("Float Tensor (float32):", tensor.float()) # float32
print("Double Tensor (float64):", tensor.double()) # float64

Boolean Tensor: tensor([False,  True,  True,  True])
Short Tensor (int16): tensor([0, 1, 2, 3], dtype=torch.int16)
Long Tensor (int64): tensor([0, 1, 2, 3])
Half Tensor (float16): tensor([0., 1., 2., 3.], dtype=torch.float16)
Float Tensor (float32): tensor([0., 1., 2., 3.])
Double Tensor (float64): tensor([0., 1., 2., 3.], dtype=torch.float64)


Convet b/w Numpy Arrays and Tensors

In [8]:
# Numpy arrays of zeros
np_array=np.zeros((5,5))
print("Numpy Arrays:\n", np_array)

# Convert Numpy to Pythorch
tensor=torch.from_numpy(np_array)
print("Tensor From Numpy Array:\n",tensor)

# Convert tensor back

numpy_back=tensor.numpy()
print("Converted Back to Numpy Array:\n", numpy_back)

Numpy Arrays:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Tensor From Numpy Array:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
Converted Back to Numpy Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Tensor Mathematics and Comparision Operations

In [9]:
x =torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

# Addition
z=x+y
print("Addition Results:",z)

# Addition using add
z1=torch.empty(3)
torch.add(x,y, out=z1)
z2=torch.add(x,y)
print("Addition using add Results:", z,z1,z2)

# Subtraction
z=x-y
print("Subtraction Result:", z)

# Divison (true division)
z=torch.true_divide(x,y)
print("Division Result:",z)

# Inplace Operations
t=torch.ones(3)
print("Before Inplace addition:", t)
t.add_(x)
print("After Inplace addition:",t)
t+=x # Another inplace addition
print("After Second inplace addition:",t)

# Exponentiation
z=x.pow(2)
print("Exponentiation (pow):",z)
z=x**2
print("Exponentiation (**):",z)

# Comparision
z=x>0
print("x>0:",z)
z=x<0
print("x<0:",z)

# Dot Product
z=torch.dot(x,y)
print("Dor Product:",z)



Addition Results: tensor([10, 10, 10])
Addition using add Results: tensor([10, 10, 10]) tensor([10., 10., 10.]) tensor([10, 10, 10])
Subtraction Result: tensor([-8, -6, -4])
Division Result: tensor([0.1111, 0.2500, 0.4286])
Before Inplace addition: tensor([1., 1., 1.])
After Inplace addition: tensor([2., 3., 4.])
After Second inplace addition: tensor([3., 5., 7.])
Exponentiation (pow): tensor([1, 4, 9])
Exponentiation (**): tensor([1, 4, 9])
x>0: tensor([True, True, True])
x<0: tensor([False, False, False])
Dor Product: tensor(46)


Matrix Multiplication and Batch Operations

In [10]:
# Matrix Multiplication using @ operator and torch.mm

m1=torch.tensor([[1,2,3]])
m2=torch.tensor([[9,8,7]])

z1=m1@torch.t(m2)
print("Matrix Multiplication (@ operator):\n", z1)
z2=torch.mm(m1, torch.t(m2))
print("Matrix Multiplication (torch.mm):\n", z2)
z3=m1.mm(torch.t(m2))
print("Matrix Multiplication (mm):\n", z3)


Matrix Multiplication (@ operator):
 tensor([[46]])
Matrix Multiplication (torch.mm):
 tensor([[46]])
Matrix Multiplication (mm):
 tensor([[46]])


In [11]:
# Matrix Exponemtiation
matrix_exp=torch.rand(5,5)
print("Matrix Multiplication:\n", matrix_exp @ matrix_exp @ matrix_exp)
print("Matrix Power 3:\n", matrix_exp.matrix_power(3))

Matrix Multiplication:
 tensor([[2.7269, 3.7515, 4.7292, 6.1857, 3.3993],
        [1.5258, 2.0464, 2.5921, 3.5241, 1.9416],
        [2.5894, 3.4355, 4.3771, 5.9963, 3.2974],
        [1.0092, 1.2721, 1.6183, 2.2792, 1.2726],
        [2.6298, 2.9542, 3.7448, 5.1247, 3.0044]])
Matrix Power 3:
 tensor([[2.7269, 3.7515, 4.7292, 6.1857, 3.3993],
        [1.5258, 2.0464, 2.5921, 3.5241, 1.9416],
        [2.5894, 3.4355, 4.3771, 5.9963, 3.2974],
        [1.0092, 1.2721, 1.6183, 2.2792, 1.2726],
        [2.6298, 2.9542, 3.7448, 5.1247, 3.0044]])


In [12]:
# Element-wise multiplication
z4=torch.mul(m1,m2)
print("Element-wise Multiplication:\n", z4)
z5=m1*m2
print("Element-wise Multiplication (alternative):\n", z4)

Element-wise Multiplication:
 tensor([[ 9, 16, 21]])
Element-wise Multiplication (alternative):
 tensor([[ 9, 16, 21]])


In [14]:
# Batch Matrix multiplication
batch=32 
n, m, p=10,20,30
tensor1=torch.rand((batch, n, m))
tensor2=torch.rand((batch, m, p))
out_bmm=torch.bmm(tensor1, tensor2) # Result Shape: (batch, n,p)
print("Batch Matrix Multiplication (first batch):\n", out_bmm[0])
print("Shape of batched multiplication result:", (tensor1@tensor2).shape)


Batch Matrix Multiplication (first batch):
 tensor([[3.9949, 3.3958, 3.9320, 3.8010, 5.2081, 4.3037, 5.3203, 4.4782, 4.1088,
         4.7826, 3.6692, 4.4272, 4.1676, 4.4411, 4.2946, 4.9192, 3.8412, 3.9426,
         4.1771, 4.5140, 4.1298, 5.3026, 4.5101, 4.4490, 3.9309, 3.5774, 5.1333,
         2.9883, 4.2787, 5.3376],
        [3.6956, 3.7734, 4.1437, 4.2491, 4.5589, 3.8867, 4.4575, 3.8127, 4.1247,
         4.6248, 3.8216, 4.2603, 3.6873, 4.7135, 4.2442, 3.9502, 4.1666, 3.7801,
         4.8304, 5.0018, 3.6584, 4.7191, 4.0945, 3.8339, 3.9426, 3.8390, 4.9567,
         3.0883, 4.3284, 4.9563],
        [4.9043, 4.9653, 6.2397, 5.2186, 6.2676, 4.4378, 6.8076, 5.6279, 4.8811,
         5.8970, 5.2702, 4.2911, 4.6307, 6.5301, 5.3191, 6.3947, 5.6046, 4.3094,
         5.4749, 6.1967, 5.1801, 5.8385, 4.5020, 4.9978, 5.3898, 5.0397, 6.5294,
         4.4848, 5.9422, 5.8620],
        [5.4134, 4.4241, 4.8428, 5.5857, 5.3111, 4.7751, 6.2568, 6.5281, 4.6570,
         6.3217, 4.7393, 5.4198, 4.4950, 5.1

Broadcasting and Other Useful Operations

In [15]:
# Broadcasting: Automatically expands smaller tensors to match larger ones
x1=torch.rand(5,5)
x2=torch.rand(5)
print("Tensor  x1:\n", x1)
print("Tensor  x2:\n", x2)
print("x1-x2:\n", x1-x2)
print("x1 raised to the power of x2:\n", x1**x2)

Tensor  x1:
 tensor([[0.9702, 0.0740, 0.1491, 0.3046, 0.8941],
        [0.2756, 0.7397, 0.3863, 0.1100, 0.3683],
        [0.4379, 0.8189, 0.2133, 0.6038, 0.2114],
        [0.6605, 0.0565, 0.8893, 0.6935, 0.9125],
        [0.8469, 0.8379, 0.7799, 0.3334, 0.1606]])
Tensor  x2:
 tensor([0.4038, 0.2460, 0.0856, 0.9858, 0.9867])
x1-x2:
 tensor([[ 0.5664, -0.1720,  0.0635, -0.6812, -0.0926],
        [-0.1282,  0.4937,  0.3007, -0.8759, -0.6184],
        [ 0.0342,  0.5729,  0.1277, -0.3820, -0.7753],
        [ 0.2568, -0.1894,  0.8037, -0.2924, -0.0742],
        [ 0.4431,  0.5919,  0.6944, -0.6524, -0.8261]])
x1 raised to the power of x2:
 tensor([[0.9879, 0.5271, 0.8497, 0.3098, 0.8955],
        [0.5943, 0.9285, 0.9218, 0.1135, 0.3732],
        [0.7165, 0.9520, 0.8762, 0.6082, 0.2158],
        [0.8458, 0.4933, 0.9900, 0.6971, 0.9136],
        [0.9351, 0.9574, 0.9790, 0.3387, 0.1646]])


In [16]:
# Sum of tensor elements along dimension 0
sum_x=torch.sum(x, dim=0)
print("Sum along dimension 0:", sum_x)

Sum along dimension 0: tensor(6)


In [18]:
# Maximum and Minimum values
value, indices=torch.max(x,dim=0)
print("Max value and index:", value, indices)

value, inices=torch.min(x,dim=0)
print("Max value and index:", value, indices)

Max value and index: tensor(3) tensor(2)
Max value and index: tensor(1) tensor(2)


In [19]:
print("Absolute values:", torch.abs(x))
print("Argmax:", torch.argmax(x, dim=0))
print("Argmin:", torch.argmin(x, dim=0))
print("Mean (Converted to float):", torch.mean(x.float(), dim=0))
print("Element-wise equality (x==y):", torch.eq(x,y))

Absolute values: tensor([1, 2, 3])
Argmax: tensor(2)
Argmin: tensor(0)
Mean (Converted to float): tensor(2.)
Element-wise equality (x==y): tensor([False, False, False])


In [20]:
# Sorting
sorted_y, indices=torch.sort(y, dim=0, descending=False)
print("Sorted y and indices:", sorted_y, indices)

Sorted y and indices: tensor([7, 8, 9]) tensor([2, 1, 0])


In [21]:
# Clamping values
print("Clamped x:", torch.clamp(x, min=0))

Clamped x: tensor([1, 2, 3])


In [22]:
# Boolean Operations
x_bool=torch.tensor([1,0,1,1.1], dtype=torch.bool)
print("Any True:",torch.any(x_bool))
print("All True:", torch.all(x_bool))

Any True: tensor(True)
All True: tensor(False)


Tensor Indexing

In [23]:
# Create a random tensor with shape (batch_size, features)
batch_size=10
features=25
x=torch.rand((batch_size, features))

# Access the first row
print("First row of tensor:", x[0,:])
# Access the Second column
print("First column of tensor:", x[0:,1])
# Access the first 10 elements of the third row
print("First 10 elements of third row:", x[2,0:10])

First row of tensor: tensor([0.0859, 0.5349, 0.3965, 0.5059, 0.9615, 0.9871, 0.3591, 0.4938, 0.2251,
        0.7282, 0.7297, 0.3894, 0.5930, 0.7405, 0.9944, 0.9662, 0.9122, 0.2420,
        0.4365, 0.5006, 0.4889, 0.7993, 0.2348, 0.6439, 0.4510])
First column of tensor: tensor([0.5349, 0.8928, 0.9907, 0.5341, 0.7713, 0.0171, 0.3878, 0.1604, 0.6292,
        0.3986])
First 10 elements of third row: tensor([0.9382, 0.9907, 0.9006, 0.9356, 0.4945, 0.4067, 0.2724, 0.2264, 0.1972,
        0.0070])


In [24]:
# Modify a specific element (set first element to 100)
x[0,0]=100
# Fancy indexing example
x1=torch.arange(10)
indices=[2,5,8]
print("Fancy indexing result:", x1[indices])
# Advancing indexing: select elements based on a condition
x2=torch.arange(10)
print("Elements where x2 <2 or x2>8:", x2[(x2<2) | (x2>8)])
print("Even numbers in x2:", x2[x2.remainder(2)==0])
# Using torch.where to select values based on a condition
print("Using torch.where:", torch.where(x2>5,x2,x2*2))

Fancy indexing result: tensor([2, 5, 8])
Elements where x2 <2 or x2>8: tensor([0, 1, 9])
Even numbers in x2: tensor([0, 2, 4, 6, 8])
Using torch.where: tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [25]:
# Reshape a tensor using view and reshape
x=torch.arange(9)
x_3x3=x.view(3,3)
print("Reshape to 3 x 3 using view:\n", x_3x3)
x_3x3=x.reshape(3,3)
print("Reshape to 3 x 3 using reshape:\n", x_3x3)

Reshape to 3 x 3 using view:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Reshape to 3 x 3 using reshape:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [27]:
# Transpose and flatten the tensor
y=x_3x3.t()
print("Flattened transposed tensor:", y.contiguous().view(9))

Flattened transposed tensor: tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [29]:
# Concatenation 
x1=torch.rand(2,5)
x2=torch.rand(2,5)
print("Concatenated along dimension 0 (rows):",torch.cat([x1,x2], dim=0))
print("Concatenated along dimension 1 (columns):",torch.cat([x1,x2], dim=0))      

Concatenated along dimension 0 (rows): tensor([[0.2793, 0.1322, 0.2553, 0.3946, 0.1120],
        [0.7378, 0.9246, 0.0344, 0.1203, 0.1733],
        [0.5399, 0.0644, 0.1179, 0.0948, 0.9875],
        [0.6719, 0.7047, 0.4549, 0.1345, 0.0446]])
Concatenated along dimension 1 (columns): tensor([[0.2793, 0.1322, 0.2553, 0.3946, 0.1120],
        [0.7378, 0.9246, 0.0344, 0.1203, 0.1733],
        [0.5399, 0.0644, 0.1179, 0.0948, 0.9875],
        [0.6719, 0.7047, 0.4549, 0.1345, 0.0446]])


In [ ]:
# Flatten the tensor using view (-1)
z=x1.view(-1)
print("Flattened tensor shape:", z.shape)

# Reshape with batch dimension
batch=64
x=torch.rand(batch, 2,5)
print("Reshaped tensor shape:",z.shape)

#Unsqueeze example (adding new dimensions)
x=torch.aranage(10)
print("Original x:", x)
print("x unsqueezed at dim 0:", x.unsqueeze(0).shape, x.unsqueeze(0))
print("x unsqueezed at dim 1:", x.unsqueeze(1).shape, x.unsqueez